name: tupange
description: A Slide Puzzle, built with Flutter <3
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.6.0

dependencies:
  animated_text_kit: ^4.2.3
  audioplayers: ^6.4.0
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4 # Annotations for code generation with Freezed
  gap: ^3.0.1
  get_it: ^8.0.2 # Dependency injection container
  injectable: ^2.5.0 # Code generator for dependency injection
  intl: ^0.19.0
  json_annotation: ^4.9.0 # Annotations for JSON serialization/deserialization
  loading_indicator: ^3.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  rive: ^0.13.20
  shared_preferences: ^2.3.3 # Local key-value storage for simple data persistence
  sqflite: ^2.4.1
  styled_widget: ^0.4.1
  supabase_auth_ui: ^0.5.4
  supabase_flutter: ^2.8.4
  textstyle_extensions: ^2.0.0-nullsafety
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13 # Tool for generating code
  floor_generator: ^1.5.0 # Code generator for Floor ORM
  flutter_lints: ^5.0.0 # Recommended lint rules for Flutter
  flutter_test:
    sdk: flutter # Testing framework for Flutter apps
  freezed: ^2.5.7 # Code generator for Freezed data classes
  injectable_generator: ^2.6.2 # Code generator for Injectable DI
  json_serializable: ^6.8.0 # Code generator for JSON serialization

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/audio/
    - assets/images/
    - assets/planets/earth/
    - assets/planets/jupiter/
    - assets/planets/mars/
    - assets/planets/mercury/
    - assets/planets/neptune/
    - assets/planets/pluto/
    - assets/planets/saturn/
    - assets/planets/uranus/
    - assets/planets/venus/

  fonts:
    - family: Freshman
      fonts:
        - asset: assets/fonts/freshman.ttf
